profile: cover.out
git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
git-branch: badges
local-prefix: github.com/tehbooom/todo
threshold:
  total: 80
exclude:
  paths:
    - ^main.go
